# Generated by Django 5.2.12 on 2026-04-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminlogins',
            table='adminlogins',
        ),
        migrations.AlterModelTable(
            name='bookings',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='rooms',
        ),
    ]
