# Generated by Django 5.2.12 on 2026-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_adminlogins_table_alter_bookings_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
