# Generated by Django 5.2.12 on 2026-04-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_remove_bookings_id_remove_rooms_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='admin_id',
            field=models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='Booking.adminlogins'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room_number',
            field=models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.CASCADE, to='Booking.rooms'),
        ),
    ]
