# Generated by Django 5.2.12 on 2026-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_bookings_admin_id_alter_bookings_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='admin_id',
        ),
    ]
