# Generated by Django 5.2.12 on 2026-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_bookings_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('requester', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=8)),
                ('dept', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
