# Generated by Django 5.2.12 on 2026-04-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_requestapplications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestApplications',
        ),
    ]
