# Generated by Django 5.2.12 on 2026-04-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_requestapplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestapplications',
            name='aim',
            field=models.CharField(max_length=20),
        ),
    ]
